name: Terraform Destroy 
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  TF_WORK_DIR: "./terraform"
jobs:
  destroy-workspace:
    name: Destroy Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_RTF_CI_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_RTF_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5
          working-directory: "${{ env.TF_WORK_DIR }}"
      - name: Terraform Init
        working-directory: "${{ env.TF_WORK_DIR }}"
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_TFSTATE_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_TFSTATE_KEY_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: >
          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" 
          -backend-config="key=${AWS_BUCKET_KEY_NAME}" 
          -backend-config="region=${AWS_REGION}"
      - name: Terraform Destroy
        working-directory: "${{ env.TF_WORK_DIR }}"
        run: terraform destroy -auto-approve